languageCode = "ja"
baseUrl = "https://ryosukeYamazaki.github.io"
title = "moaiの走り書き"
theme = "anubis"
paginate = 10
disqusShortname = "yourdiscussshortname"
# googleAnalytics = "UA-123-45"
enableRobotsTXT = true

[[menu.main]]
identifier = "archive"
name = "moaiの走り書き"
title = "Archive"
url = "/posts/"
weight = 0

[params]
author = "moai"
description = ""
images = [ "images/og-featured.png" ]
# customCSS = [ "css/my.css" ]
# customJS = [ "js/main.js" ]
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "light-without-switcher"
readMore = false

[markup.goldmark.renderer]
unsafe = true