languageCode = "ja"
baseUrl = "https://ryosukeYamazaki.github.io"
title = "moaiの走り書き"
theme = "anubis"
paginate = 10
disqusShortname = "yourdiscussshortname"
googleAnalytics = "G-TZB8933TSH"
enableRobotsTXT = true

[[menu.main]]
identifier = "archive"
name = "moaiの走り書き"
title = "Archive"
url = "/posts/"
weight = 0

[params]
author = "moai"
description = "moaiの走り書き"
images = [ "images/moai.png" ]
# customCSS = [ "css/my.css" ]
# customJS = [ "js/main.js" ]
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "auto"
readMore = true

[markup.goldmark.renderer]
unsafe = true
hardWraps = true