languageCode = "ja"
baseUrl = "https://ryosukeYamazaki.github.io"
title = "moaiの走り書き"
theme = "anubis"
paginate = 10
disqusShortname = "https-ryosukeyamazaki-github-io"
googleAnalytics = "G-TZB8933TSH"
enableRobotsTXT = true
hasCJKLanguage = true
summaryLength = 140

[[params.social]]
id = "github"
url = "https://github.com/ryosukeYamazaki"

[[params.social]]
id = "twitter"
url = "https://twitter.com/moaieee"

[[menu.main]]
identifier = "about"
name = "about"
title = "About"
url = "/about/"
weight = 0

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
title = "Tags"
weight = 0

[[menu.main]]
identifier = "archive"
name = "Archive"
title = "Archive"
url = "/posts/"
weight = 0

[taxonomies]
category = "categories"
tag = "tags"

[params]
author = "moai"
description = "moaiの走り書き"
images = [ "images/moai.png" ]
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "auto"
readMore = true

[markup.goldmark.renderer]
unsafe = true
hardWraps = true